"""Resend email helper — sends completed council documents to the requester."""
import base64
import os
from pathlib import Path

import resend

MAX_ATTACH_BYTES = 8 * 1024 * 1024  # 8 MB — attach combined PDF if under this


def send_documents_email(
    to_email: str,
    meeting_title: str,
    files: list[dict],           # [{"name": str, "signed_url": str, "path": Path}]
    combined_pdf_path: Path | None,
    combined_signed_url: str | None,
) -> None:
    resend.api_key = os.environ["RESEND_API_KEY"]
    from_addr = os.environ["FROM_EMAIL"]

    combined_btn = ""
    if combined_signed_url:
        combined_btn = (
            f'<p style="margin:24px 0">'
            f'<a href="{combined_signed_url}" '
            f'style="background:#2D6A4F;color:#fff;padding:12px 24px;border-radius:6px;'
            f'text-decoration:none;font-weight:bold;display:inline-block">'
            f'Download Combined PDF</a></p>'
        )

    doc_items_html = "".join(
        f'<li style="padding:4px 0">'
        f'<a href="{f["signed_url"]}" style="color:#2D6A4F">{f["name"]}</a></li>'
        for f in files
    )

    doc_items_text = "\n".join(f'• {f["name"]}' for f in files)

    html_body = f"""<!DOCTYPE html>
<html>
<body style="font-family:system-ui,sans-serif;margin:0;padding:0;background:#F9FAFB">
  <div style="max-width:600px;margin:32px auto;background:#fff;border-radius:8px;
              overflow:hidden;box-shadow:0 1px 3px rgba(0,0,0,.1)">
    <div style="background:#2D6A4F;padding:20px 24px">
      <h1 style="color:#fff;margin:0;font-size:18px;font-weight:600">
        City of Mitcham — Supporting Documents
      </h1>
    </div>
    <div style="padding:24px">
      <p style="color:#374151;margin-top:0">
        Your supporting documents for <strong>{meeting_title}</strong> are ready.
      </p>
      {combined_btn}
      <h3 style="color:#374151;font-size:14px;text-transform:uppercase;
                 letter-spacing:.05em;margin-top:28px">Individual Documents</h3>
      <ul style="padding-left:20px;color:#374151;line-height:1.8;margin:8px 0">
        {doc_items_html}
      </ul>
      <p style="color:#9CA3AF;font-size:12px;margin-top:32px;
                border-top:1px solid #E5E7EB;padding-top:16px">
        Download links expire in 24 hours.<br>
        Generated by the Mitcham Council Agenda Tool ·
        <a href="https://github.com/dpkruse/mitcham-council-scraper"
           style="color:#9CA3AF">GitHub</a>
      </p>
    </div>
  </div>
</body>
</html>"""

    text_body = (
        f"Your supporting documents for {meeting_title} are ready.\n\n"
        f"{doc_items_text}\n\n"
        f"Download links (valid 24 h) are in the HTML version of this email.\n"
        f"Generated by the Mitcham Council Agenda Tool.\n"
        f"https://github.com/dpkruse/mitcham-council-scraper\n"
    )

    params: dict = {
        "from": from_addr,
        "to": [to_email],
        "subject": f"Your Mitcham Council supporting documents — {meeting_title}",
        "html": html_body,
        "text": text_body,
    }

    # Attach combined PDF directly if it fits within the size limit
    if combined_pdf_path and combined_pdf_path.exists():
        if combined_pdf_path.stat().st_size <= MAX_ATTACH_BYTES:
            with open(combined_pdf_path, "rb") as fh:
                params["attachments"] = [
                    {
                        "filename": combined_pdf_path.name,
                        "content": base64.b64encode(fh.read()).decode(),
                    }
                ]

    resend.Emails.send(params)
