"""pdf_combiner.py
Combines downloaded supporting-document PDFs into a single file with:
- A grouped cover/index page (by agenda item)
- A per-document cover page before each PDF
- PDF bookmarks for quick navigation
- Clickable internal links from index rows to cover pages
- A footer crediting the tool
- A clickable link to the full meeting agenda
"""
import io
import logging
import os
import re
from collections import OrderedDict
from datetime import datetime

from pypdf import PdfWriter, PdfReader
from pypdf.annotations import Link
from reportlab.pdfgen import canvas as rl_canvas
from reportlab.lib.pagesizes import A4


logger = logging.getLogger(__name__)

GITHUB_URL = 'https://github.com/dpkruse/mitcham-council-scraper'
GITHUB_DISPLAY = 'github.com/dpkruse/mitcham-council-scraper'


def _display_title(entry):
    """Strip 'Supporting Document N:' prefix and prepend 'Supporting document — '."""
    raw = entry.get('title', os.path.basename(entry['filepath']))
    stripped = re.sub(
        r'^Supporting Document \d+\s*[-:]?\s*', '', raw,
        flags=re.IGNORECASE,
    ).strip()
    return f'Supporting document \u2014 {stripped}'


def _clean_descriptor(item_descriptor):
    """Strip leading sub-item digit (e.g. '4 Library Opening Hours' → 'Library Opening Hours')."""
    return re.sub(r'^\d+\s+', '', item_descriptor).strip()


def _wrap_lines(text, c, font_name, font_size, max_width):
    """Split text into lines that each fit within max_width points."""
    words = text.split()
    lines, current = [], ''
    for word in words:
        test = (current + ' ' + word).strip()
        if c.stringWidth(test, font_name, font_size) <= max_width:
            current = test
        else:
            if current:
                lines.append(current)
            current = word
    if current:
        lines.append(current)
    return lines or [text]


def _build_index_page(groups, page_map, meeting_title, run_date, meeting_url):
    """Return (BytesIO, link_records) for the index/cover page PDF.

    link_records: list of (filepath, x1, y1, x2, y2, page_in_index)
    where coordinates are in PDF points (bottom-left origin) and
    page_in_index is 0-based within the index PDF.
    """
    width, height = A4
    buf = io.BytesIO()
    c = rl_canvas.Canvas(buf, pagesize=A4)

    current_index_page = 0
    link_records = []

    # --- Heading (word-wrapped) ---
    heading_text = f'City of Mitcham \u2014 {meeting_title}'
    heading_lines = _wrap_lines(heading_text, c, 'Helvetica-Bold', 15, width - 80)
    c.setFont('Helvetica-Bold', 15)
    for i, line in enumerate(heading_lines):
        c.drawString(40, height - 50 - i * 19, line)

    y_subhead = height - 50 - (len(heading_lines) - 1) * 19 - 19
    c.setFont('Helvetica', 10)
    c.drawString(40, y_subhead, f'{run_date}  \u00b7  Supporting Documents')

    y = y_subhead - 22

    # --- Agenda link (meeting title as clickable text) ---
    if meeting_url:
        c.setFont('Helvetica', 9)
        c.setFillColorRGB(0.1, 0.3, 0.65)
        link_label = f'Full agenda: {meeting_title}'
        c.drawString(40, y, link_label)
        link_width = c.stringWidth(link_label, 'Helvetica', 9)
        c.linkURL(meeting_url, (40, y - 2, 40 + link_width, y + 9), relative=0)
        c.setFillColorRGB(0, 0, 0)
        y -= 16

    # --- Rule ---
    y -= 4
    c.line(40, y, width - 40, y)
    y -= 14

    # --- Grouped table ---
    for (item_number, item_descriptor), entries in groups.items():
        if y < 80:
            c.showPage()
            current_index_page += 1
            y = height - 55

        # Item group heading
        clean_desc = _clean_descriptor(item_descriptor) if item_descriptor else ''
        heading = (f'{item_number}  {clean_desc}'.strip()
                   if clean_desc else item_number)
        c.setFont('Helvetica-Bold', 10)
        c.drawString(40, y, heading)
        y -= 3
        c.line(40, y, width - 40, y)
        y -= 13

        # Document rows
        c.setFont('Helvetica', 9)
        for entry in entries:
            if y < 80:
                c.showPage()
                current_index_page += 1
                y = height - 55
                c.setFont('Helvetica', 9)

            title = _display_title(entry)
            if len(title) > 76:
                title = title[:73] + '...'
            pg = str(page_map.get(entry['filepath'], '?'))
            c.drawString(52, y, title)
            c.drawRightString(width - 40, y, pg)

            # Record bounding box for internal link annotation
            link_records.append((
                entry['filepath'],
                52, y - 3, width - 40, y + 10,
                current_index_page,
            ))

            y -= 13

        y -= 4  # extra gap between groups

    # --- Three-line footer ---
    c.setFont('Helvetica', 8)
    c.setFillColorRGB(0.5, 0.5, 0.5)
    c.drawCentredString(width / 2, 52, 'Generated by Mitcham Council supporting document scraper')
    c.drawCentredString(width / 2, 40, 'Scraper written by Councillor Darren Kruse')

    # Third line: "Code online at <clickable link>"
    prefix = 'Code online at '
    full_line = prefix + GITHUB_DISPLAY
    c.drawCentredString(width / 2, 28, full_line)
    full_w = c.stringWidth(full_line, 'Helvetica', 8)
    prefix_w = c.stringWidth(prefix, 'Helvetica', 8)
    link_w = c.stringWidth(GITHUB_DISPLAY, 'Helvetica', 8)
    line_start_x = width / 2 - full_w / 2
    link_x1 = line_start_x + prefix_w
    link_x2 = link_x1 + link_w
    c.linkURL(GITHUB_URL, (link_x1, 26, link_x2, 36), relative=0)

    c.setFillColorRGB(0, 0, 0)

    c.save()
    buf.seek(0)
    return buf, link_records


def _build_cover_page(entry, meeting_title, run_date, n, m):
    """Return a BytesIO containing one per-document cover page."""
    width, height = A4
    buf = io.BytesIO()
    c = rl_canvas.Canvas(buf, pagesize=A4)

    item_number = entry.get('item_number', '')
    item_descriptor = entry.get('item_descriptor', '')
    clean_desc = _clean_descriptor(item_descriptor) if item_descriptor else ''
    doc_title = _display_title(entry)

    # Top grey line
    c.setFont('Helvetica', 8)
    c.setFillColorRGB(0.55, 0.55, 0.55)
    c.drawCentredString(
        width / 2, height - 60,
        f'City of Mitcham  \u00b7  {meeting_title}  \u00b7  {run_date}',
    )
    c.setFillColorRGB(0, 0, 0)

    # Item line (medium bold)
    item_line = (f'Item {item_number}  \u00b7  {clean_desc}'
                 if clean_desc else f'Item {item_number}')
    c.setFont('Helvetica-Bold', 12)
    c.drawCentredString(width / 2, height / 2 + 50, item_line)

    # Document title (large bold, word-wrapped)
    lines = _wrap_lines(doc_title, c, 'Helvetica-Bold', 16, width - 80)
    line_height = 22
    title_top = height / 2 + 10
    c.setFont('Helvetica-Bold', 16)
    for i, line in enumerate(lines):
        c.drawCentredString(width / 2, title_top - i * line_height, line)

    # Bottom note
    c.line(40, 60, width - 40, 60)
    c.setFont('Helvetica', 9)
    c.setFillColorRGB(0.55, 0.55, 0.55)
    c.drawCentredString(width / 2, 45, f'Supporting document {n} of {m} for this item')
    c.setFillColorRGB(0, 0, 0)

    c.save()
    buf.seek(0)
    return buf


def combine_pdfs(pdf_entries, output_path, meeting_title, run_date=None, meeting_url=None):
    """Merge PDFs with a grouped cover page, per-document covers, and bookmarks.

    Args:
        pdf_entries: list of dicts with keys:
            'filepath'        — path to the PDF file
            'item_number'     — agenda item number, e.g. '10.4'
            'item_descriptor' — agenda item title, e.g. 'Library Opening Hours' (optional)
            'title'           — raw document title (optional)
        output_path:  full path for the output combined PDF
        meeting_title: displayed in headings
        run_date:     date string (defaults to today)
        meeting_url:  Player.aspx URL shown as a clickable link (optional)

    Returns:
        output_path on success, None if no valid input files exist.
    """
    if run_date is None:
        run_date = datetime.now().strftime('%Y-%m-%d')

    valid_entries = [e for e in pdf_entries if os.path.isfile(e['filepath'])]
    if not valid_entries:
        return None

    # --- Group entries by (item_number, item_descriptor) preserving order ---
    groups = OrderedDict()
    for entry in valid_entries:
        key = (entry.get('item_number', ''), entry.get('item_descriptor', ''))
        groups.setdefault(key, []).append(entry)

    # --- Precompute N-of-M counts for cover pages ---
    cover_position = {}  # filepath -> (n, m)
    for entries in groups.values():
        m = len(entries)
        for i, entry in enumerate(entries):
            cover_position[entry['filepath']] = (i + 1, m)

    # --- Pass 1: calculate 1-indexed page numbers for the index ToC ---
    # Page 1 = index. Then each entry: 1 cover page + its own pages.
    page_map = {}
    current_page = 2
    for entry in valid_entries:
        page_map[entry['filepath']] = current_page
        current_page += 1  # cover page
        try:
            current_page += len(PdfReader(entry['filepath']).pages)
        except Exception as e:
            logger.warning(f'[COMBINER] Could not read page count for {entry["filepath"]}: {e}')
            current_page += 1

    # --- Build index page ---
    index_buf, link_records = _build_index_page(
        groups, page_map, meeting_title, run_date, meeting_url
    )

    # --- Assemble writer ---
    writer = PdfWriter()

    # Index page(s)
    index_reader = PdfReader(index_buf)
    for page in index_reader.pages:
        writer.add_page(page)

    # Track 0-indexed page positions for bookmarks
    bookmark_page = {}      # filepath -> 0-indexed page of its cover
    group_first_page = {}   # group key -> 0-indexed page of first cover in group

    page_idx = len(index_reader.pages)  # first page after index

    for entry in valid_entries:
        key = (entry.get('item_number', ''), entry.get('item_descriptor', ''))
        n, m = cover_position[entry['filepath']]

        # Cover page
        cover_buf = _build_cover_page(entry, meeting_title, run_date, n, m)
        cover_pages = PdfReader(cover_buf).pages
        for page in cover_pages:
            writer.add_page(page)

        bookmark_page[entry['filepath']] = page_idx
        group_first_page.setdefault(key, page_idx)
        page_idx += len(cover_pages)

        # Document pages
        try:
            doc_pages = PdfReader(entry['filepath']).pages
            for page in doc_pages:
                writer.add_page(page)
            page_idx += len(doc_pages)
        except Exception as e:
            logger.warning(f'[COMBINER] Could not read pages from {entry["filepath"]}: {e}')
            page_idx += 1

    # --- Internal link annotations: index rows → cover pages ---
    for filepath, x1, y1, x2, y2, index_page_num in link_records:
        if filepath not in bookmark_page:
            continue
        try:
            annotation = Link(
                rect=(x1, y1, x2, y2),
                target_page_index=bookmark_page[filepath],
            )
            writer.add_annotation(page_number=index_page_num, annotation=annotation)
        except Exception as e:
            logger.warning(f'[COMBINER] Could not add link annotation for {filepath}: {e}')

    # --- PDF bookmarks (outline) ---
    for (item_number, item_descriptor), entries in groups.items():
        clean_desc = _clean_descriptor(item_descriptor) if item_descriptor else ''
        heading = (f'{item_number}  {clean_desc}'.strip()
                   if clean_desc else item_number)
        try:
            parent = writer.add_outline_item(
                heading, group_first_page[(item_number, item_descriptor)]
            )
            for entry in entries:
                writer.add_outline_item(
                    _display_title(entry),
                    bookmark_page[entry['filepath']],
                    parent=parent,
                )
        except AttributeError:
            parent = writer.add_bookmark(
                heading, group_first_page[(item_number, item_descriptor)]
            )
            for entry in entries:
                writer.add_bookmark(
                    _display_title(entry),
                    bookmark_page[entry['filepath']],
                    parent=parent,
                )

    with open(output_path, 'wb') as f:
        writer.write(f)

    return output_path
